---
title: "Data Science Specialism - R Programming"
output:
  html_document:
    df_print: paged
---

# Subsetting and Sorting Data
https://www.coursera.org/learn/data-cleaning/home/welcome

**Further information**

http://www.biostat.jhsph.edu/~ajaffe/lec_winterR/Lecture%202.pdf


```{r setup}
# {r setup}

mod3Dir <- "~/repositories/learning/data-science-coursera/03-get-clean-data"
dataDir <- "data"

setwd(mod3Dir)
if(!file.exists(dataDir)) { dir.create(dataDir) }

# set the root directory for this notebook
knitr::opts_knit$set(root.dir = paste(mod3Dir, dataDir, sep = "/"))

# setup simple data frame for this session
set.seed(13435)
x <- data.frame("var1"=sample(1:5), "var2"=sample(6:10), "var3"=sample(11:15))
x <- x[sample(1:5),];x$var2[c(1,3)]=NA

# install the prerequisites (if not already installed)
if("plyr" %in% rownames(installed.packages()) == FALSE) {install.packages("plyr")}
```

<br />

### Quick Review of Simple Subsetting

#### Create a simple data frame

```{r}
x
```

<br />

#### Do some simple sub-setting on it

```{r}
# get the first column
x[,1]

# get the first row
x[1,]

# get a column by variable name
x[,"var1"]

# get first four rows of a particular variable
x[1:4,"var2"]
```


<br />

#### Sub-setting using logical statements

```{r}
# subsetting using comparison operators and also combinatorials such as "and" or "or"
x[(x$var1 <= 3 & x$var3 > 11),]

x[(x$var1 <= 3 | x$var3 > 15),]
```

<br />

#### Dealing with NAs in subsetting

```{r}
# subsetting NOT dealing with the NAs
x[x$var2 > 8, ]

# subsetting dealing with the NAs
x[which(x$var2 > 8), ]

```

<br />

### Quick Review of Sorting

```{r}
# sorting
sort(x$var1)
sort(x$var1, decreasing = TRUE)

# dealing with NAs in sorting
sort(x$var2)
sort(x$var2, na.last = TRUE)
sort(x$var2, na.last = FALSE)

# Ordering a dataframe
x[order(x$var1),]

# ordering by multiple variables
x[order(x$var1, x$var3),]
```

<br />

#### Using the ```plyr``` package to sort and order
```{r}
library(plyr)
arrange(x, var1)
arrange(x, desc(var1))
```

### Adding Rows and Columns to Dataframes

```{r}
x$var4 <- rnorm(5)
x

# or you can do it using column bind
y <- cbind(x, rnorm(5))
y

# and now with rows
z <- rbind(x, c(6, 11, 16, rnorm(1)))
z
```
